# These are supported funding model platforms.

github: your-github-username

patreon: ""

open_collective: ""

ko_fi: ""

tidelift: ""

community_bridge: ""

liberapay: ""

issuehunt: ""

otechie: ""

custom:
  - "https://your-website.example/support"
  - "https://buymeacoffee.com/yourusername"
